#!/bin/sh
# create by chris1111
# Copyright (c) 2021 chris1111 All rights reserved.
rm -rf /Private/tmp/Themes.zip
rm -rf /Private/tmp/master.zip
Sleep 1
# Download Acidanthera OcBinaryData
echo "Download Acidanthera OcBinaryData without Drivers and .mp3 files"
Sleep 1
curl -L --progress-bar https://github.com/acidanthera/OcBinaryData/archive/refs/heads/master.zip -o /Private/tmp/master.zip
echo "Done"
ditto -x -k --sequesterRsrc --rsrc /Private/tmp/master.zip $HOME/Downloads
Sleep 1
echo "Done"
Sleep 1
rm -rf $HOME/Downloads/OcBinaryData-master/Drivers
rm -rf $HOME/Downloads/OcBinaryData-master/Resources/Audio/*.mp3
Sleep 1
ditto -x -k --sequesterRsrc --rsrc /Private/tmp/Resources.zip /Private/tmp
Sleep 1
cp -RP /Private/tmp/Resources/image/chris1111 $HOME/Downloads/OcBinaryData-master/Resources/Image
Sleep 1
rm -rf /Private/tmp/master.zip
rm -rf /Private/tmp/Resources
rm -rf /Private/tmp/Resources.zip
rm -rf /Private/tmp/Themes.zip
Open $HOME/Downloads/OcBinaryData-master/Resources/Image/chris1111
